# Generated by Django 5.2.14 on 2026-08-01 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coach',
            options={'ordering': ['name'], 'verbose_name_plural': 'Coaches'},
        ),
    ]
