# Generated by Django 5.2.14 on 2026-06-09 12:36

from django.db import migrations, models


def safe_db_operations(apps, schema_editor):
    from django.db import connection, transaction
    
    # We will try the first query, and if it fails, we try the fallback.
    # We ignore errors for removing columns.
    queries = [
        # linkedin -> linkedIn
        ('ALTER TABLE coach_coach RENAME COLUMN "linkedin" TO "linkedIn";',
         'ALTER TABLE coach_coach ADD COLUMN "linkedIn" varchar(200) NOT NULL DEFAULT \'\';'),
        
        # image -> photo
        ('ALTER TABLE coach_coach RENAME COLUMN "image" TO "photo";',
         'ALTER TABLE coach_coach ADD COLUMN "photo" varchar(100) DEFAULT NULL;'),
        
        # drop event_id
        ('ALTER TABLE coach_coach DROP COLUMN "event_id";', None),
        
        # drop featured
        ('ALTER TABLE coach_coach DROP COLUMN "featured";', None),
        
        # drop updated_at
        ('ALTER TABLE coach_coach DROP COLUMN "updated_at";', None),
        
        # add active
        ('ALTER TABLE coach_coach ADD COLUMN "active" boolean NOT NULL DEFAULT true;', None),
        
        # add role
        ('ALTER TABLE coach_coach ADD COLUMN "role" varchar(200) NOT NULL DEFAULT \'\';', None),
        
        # alter name (postgres)
        ('ALTER TABLE coach_coach ALTER COLUMN "name" TYPE varchar(200);', None),
    ]
    
    with connection.cursor() as cursor:
        for try_sql, fallback_sql in queries:
            try:
                with transaction.atomic():
                    if connection.vendor == 'sqlite':
                        if 'ALTER COLUMN' in try_sql:
                            continue  # SQLite doesn't support ALTER COLUMN TYPE easily
                        cursor.execute(try_sql.replace('"', ''))
                    else:
                        cursor.execute(try_sql)
            except Exception:
                if fallback_sql:
                    try:
                        with transaction.atomic():
                            if connection.vendor == 'sqlite':
                                cursor.execute(fallback_sql.replace('"', ''))
                            else:
                                cursor.execute(fallback_sql)
                    except Exception:
                        pass


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RenameField(
                    model_name='coach',
                    old_name='linkedin',
                    new_name='linkedIn',
                ),
                migrations.RenameField(
                    model_name='coach',
                    old_name='image',
                    new_name='photo',
                ),
                migrations.RemoveField(
                    model_name='coach',
                    name='event',
                ),
                migrations.RemoveField(
                    model_name='coach',
                    name='featured',
                ),
                migrations.RemoveField(
                    model_name='coach',
                    name='updated_at',
                ),
                migrations.AddField(
                    model_name='coach',
                    name='active',
                    field=models.BooleanField(default=True),
                ),
                migrations.AddField(
                    model_name='coach',
                    name='role',
                    field=models.CharField(blank=True, max_length=200),
                ),
                migrations.AlterField(
                    model_name='coach',
                    name='bio',
                    field=models.TextField(blank=True),
                ),
                migrations.AlterField(
                    model_name='coach',
                    name='name',
                    field=models.CharField(max_length=200),
                ),
            ],
            database_operations=[
                migrations.RunPython(
                    code=safe_db_operations,
                ),
            ]
        ),
    ]
