# Generated by Django 5.2.14 on 2026-06-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coach',
            old_name='linkedin',
            new_name='linkedIn',
        ),
        migrations.RenameField(
            model_name='coach',
            old_name='image',
            new_name='photo',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='event',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='coach',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='role',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='coach',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='coach',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
