# Generated by Django 5.2.15 on 2026-06-22 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_header', models.CharField(blank=True, help_text='Header text shown at the top of the form', max_length=500)),
                ('text_description', models.TextField(blank=True, help_text='Introductory description shown to applicants')),
                ('confirmation_mail', models.TextField(blank=True, help_text='Email body sent to applicants after submission')),
                ('is_open', models.BooleanField(default=True, help_text='Whether this form is currently accepting submissions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(help_text='The event this application form belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='application_forms', to='core.event')),
            ],
            options={
                'verbose_name': 'Form',
                'verbose_name_plural': 'Forms',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The question text', max_length=500)),
                ('help_text', models.CharField(blank=True, help_text='Optional help text shown below the question', max_length=500)),
                ('question_type', models.CharField(choices=[('text', 'Text (short answer)'), ('paragraph', 'Paragraph (long answer)'), ('choices', 'Multiple choice'), ('email', 'Email'), ('url', 'URL'), ('number', 'Number')], default='text', max_length=20)),
                ('choices', models.TextField(blank=True, help_text="One choice per line (only used for 'Multiple choice' question type)")),
                ('is_required', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='applications.form')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_email', models.EmailField(help_text='Email of the person who submitted this answer', max_length=254)),
                ('answer', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='applications.question')),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
