# Generated by Django 5.2.15 on 2026-06-22 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_first_name', models.CharField(max_length=200)),
                ('lead_last_name', models.CharField(blank=True, max_length=200)),
                ('lead_email', models.EmailField(max_length=254)),
                ('team_members', models.JSONField(blank=True, default=list, help_text='List of {first_name, last_name, email} dicts for co-organisers')),
                ('prerequisites_confirmed', models.BooleanField(default=False)),
                ('workshop_type', models.CharField(choices=[('remote', 'Remote'), ('in_person', 'In-Person')], default='in_person', max_length=20)),
                ('commitment_signed', models.BooleanField(default=False)),
                ('has_organized_before', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('previous_event', models.ForeignKey(blank=True, help_text='If they organised before, which event?', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returning_organizers', to='core.event')),
            ],
            options={
                'verbose_name': 'Organizer application',
                'verbose_name_plural': 'Organizer applications',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
