# Generated by Django 5.2.14 on 2026-08-01 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_organizerapplication'),
        ('content', '0002_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('motivation', models.TextField()),
                ('experience', models.TextField(blank=True)),
                ('expected_attendees', models.PositiveIntegerField(default=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
            ],
            options={
                'verbose_name': 'Event application',
                'verbose_name_plural': 'Event applications',
                'ordering': ['-id'],
            },
        ),
        migrations.AlterField(
            model_name='answer',
            name='applicant_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='form',
            name='confirmation_mail',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='event',
            field=models.ForeignKey(help_text='The event this application form belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='application_forms', to='content.event'),
        ),
        migrations.AlterField(
            model_name='form',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='text_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='text_header',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='organizerapplication',
            name='previous_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returning_organizers', to='content.event'),
        ),
        migrations.AlterField(
            model_name='organizerapplication',
            name='team_members',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='question',
            name='choices',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='help_text',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
