# Generated by Django 5.2.15 on 2026-08-06 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_eventapplication_alter_answer_applicant_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizerValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OrganizerExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organizer_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='applications.organizerapplication')),
            ],
        ),
    ]
