# Generated by Django 5.2.5 on 2026-08-11 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_organizervalue_organizerexperience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizerexperience',
            name='organizer_application',
        ),
        migrations.DeleteModel(
            name='OrganizerValue',
        ),
        migrations.DeleteModel(
            name='OrganizerExperience',
        ),
    ]
