# Generated by Django 5.2.5 on 2026-08-11 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_remove_organizerexperience_organizer_application_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Optional banner image displayed at the top of the form.', null=True, upload_to='forms/heroes/'),
        ),
        migrations.AlterField(
            model_name='form',
            name='confirmation_mail',
            field=models.TextField(blank=True, help_text='Email text sent to the applicant after submission.'),
        ),
        migrations.AlterField(
            model_name='form',
            name='text_description',
            field=models.TextField(blank=True, help_text='Detailed description or instructions for the applicants.'),
        ),
        migrations.AlterField(
            model_name='form',
            name='text_header',
            field=models.CharField(blank=True, help_text='The main heading for the application form.', max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='choices',
            field=models.TextField(blank=True, help_text="Only used if question type is 'Multiple choice'. Enter options separated by commas (e.g. 'Option A, Option B, Option C')."),
        ),
        migrations.AlterField(
            model_name='question',
            name='help_text',
            field=models.CharField(blank=True, help_text='Additional instructions or context for the applicant.', max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='is_required',
            field=models.BooleanField(default=True, help_text='If checked, the applicant must answer this question.'),
        ),
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Lower numbers appear first.'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'Text (short answer)'), ('paragraph', 'Paragraph (long answer)'), ('choices', 'Multiple choice'), ('email', 'Email'), ('url', 'URL'), ('number', 'Number')], default='text', help_text='Determines the input type shown to the applicant.', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(help_text="The question being asked (e.g. 'What is your current occupation?').", max_length=500),
        ),
    ]
