# Generated by Django 5.2.14 on 2026-09-11 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_form_hero_image_alter_form_confirmation_mail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizerapplication',
            name='target_country',
            field=models.CharField(blank=True, help_text='Target country for new organizers', max_length=200),
        ),
        migrations.AddField(
            model_name='organizerapplication',
            name='target_state',
            field=models.CharField(blank=True, help_text='Target state/region for new organizers', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='choices',
            field=models.TextField(blank=True, help_text="Only used if question type is 'Multiple choice'. Enter each option on a new line."),
        ),
    ]
