# Generated by Django 5.2.14 on 2026-09-29 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_organizerapplication_target_country_and_more'),
        ('content', '0015_alter_event_custom_html_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventapplication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='eventapplication',
            name='event',
            field=models.ForeignKey(blank=True, help_text='The event applied for', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_applications', to='content.event'),
        ),
        migrations.AddField(
            model_name='eventapplication',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_applications', to='applications.form'),
        ),
        migrations.AlterField(
            model_name='eventapplication',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='eventapplication',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='eventapplication',
            name='expected_attendees',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='eventapplication',
            name='full_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='eventapplication',
            name='motivation',
            field=models.TextField(blank=True),
        ),
    ]
