# Generated by Django 5.2.14 on 2026-09-29 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_eventapplication_created_at_eventapplication_event_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventapplication',
            name='city',
        ),
        migrations.RemoveField(
            model_name='eventapplication',
            name='country',
        ),
        migrations.RemoveField(
            model_name='eventapplication',
            name='expected_attendees',
        ),
        migrations.RemoveField(
            model_name='eventapplication',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='eventapplication',
            name='motivation',
        ),
        migrations.AddField(
            model_name='answer',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='applications.eventapplication'),
        ),
    ]
