# Generated by Django 5.2.17 on 2026-10-08 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_remove_eventapplication_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizerapplication',
            name='expected_attendees',
            field=models.PositiveIntegerField(default=50, help_text='Expected number of attendees the organizer plans to host.'),
        ),
    ]
