# Generated by Django 5.2.14 on 2026-06-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('interest', models.CharField(choices=[('attend', 'Attend an event'), ('coach', 'Volunteer as a coach'), ('sponsor', 'Sponsor Python Weekend'), ('other', 'Something else')], default='other', max_length=30)),
                ('message', models.TextField()),
                ('read', models.BooleanField(default=False, help_text='Mark when the message has been reviewed')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
