# Generated by Django 5.2.15 on 2026-06-22 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('interest', models.CharField(choices=[('attend', 'Attend an event'), ('coach', 'Volunteer as a coach'), ('sponsor', 'Sponsor Python Weekend'), ('other', 'Something else')], default='other', max_length=30)),
                ('message', models.TextField()),
                ('read', models.BooleanField(default=False, help_text='Mark when the message has been reviewed')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Internal name for this content block', max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('content', models.TextField(blank=True, help_text='HTML or plain text content')),
                ('page', models.CharField(blank=True, help_text="Which page this content belongs to (e.g. 'home', 'about')", max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Website content',
                'verbose_name_plural': 'Website contents',
                'ordering': ['page', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('user', models.ForeignKey(blank=True, help_text='Optional link to a Django user account.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizer_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(unique=True)),
                ('tagline', models.CharField(blank=True, help_text="Short headline in the hero, e.g. 'Build your first app this weekend!'", max_length=300)),
                ('image', models.ImageField(blank=True, help_text='Banner image shown on the event card and detail page hero', null=True, upload_to='events/')),
                ('event_email', models.EmailField(blank=True, help_text='Public contact email for this event, e.g. lagos@djangogirls.org', max_length=254)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=300)),
                ('venue_name', models.CharField(blank=True, help_text='e.g. Code Campus Nigeria, Floor 3', max_length=300)),
                ('city', models.CharField(blank=True, max_length=200)),
                ('country', models.CharField(blank=True, help_text='Country where the event takes place', max_length=200)),
                ('description', models.TextField(blank=True, help_text='General description shown above the schedule')),
                ('day1_title', models.CharField(blank=True, help_text='e.g. Installation Party & Setup', max_length=200)),
                ('day1_schedule', models.TextField(blank=True, help_text='One item per line...')),
                ('day2_title', models.CharField(blank=True, help_text='e.g. Python & Django Workshop', max_length=200)),
                ('day2_schedule', models.TextField(blank=True, help_text='One item per line')),
                ('day3_title', models.CharField(blank=True, help_text='e.g. Project Showcase...', max_length=200)),
                ('day3_schedule', models.TextField(blank=True, help_text='One item per line...')),
                ('what_you_learn', models.TextField(blank=True)),
                ('who_should_apply', models.TextField(blank=True)),
                ('faq', models.TextField(blank=True)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('application_open', models.BooleanField(default=True, help_text='Show the Register Interest button on the event page')),
                ('is_visible', models.BooleanField(default=True, help_text='Whether this event is visible on the public website')),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, help_text='The approved event organizer responsible for this specific execution.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_events', to=settings.AUTH_USER_MODEL)),
                ('organizers', models.ManyToManyField(blank=True, help_text='Organizers responsible for this event.', related_name='events', to='core.organizer')),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'List of events',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Menu item label', max_length=200)),
                ('url', models.CharField(blank=True, help_text='URL this menu item links to', max_length=500)),
                ('position', models.PositiveSmallIntegerField(default=0, help_text='Order of the menu item (lower = first)')),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent menu item for dropdown/nested menus', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.websitemenu')),
            ],
            options={
                'verbose_name': 'Website menu',
                'verbose_name_plural': 'Website menus',
                'ordering': ['position'],
            },
        ),
    ]
