# Generated by Django 5.2.14 on 2026-08-01 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_eventapplication_alter_answer_applicant_email_and_more'),
        ('core', '0002_create_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='organizers',
        ),
        migrations.RemoveField(
            model_name='event',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='organizer',
            name='user',
        ),
        migrations.DeleteModel(
            name='WebsiteContent',
        ),
        migrations.RemoveField(
            model_name='websitemenu',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Organizer',
        ),
        migrations.DeleteModel(
            name='WebsiteMenu',
        ),
    ]
