# Generated by Django 5.2.5 on 2026-08-11 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_newsletter_subscriber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newsletter',
        ),
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
