# Generated by Django 5.2.14 on 2026-10-07 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_newsletter_delete_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='replied_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the last reply was sent', null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='reply',
            field=models.TextField(blank=True, help_text='Type a reply here and save to send an email response to the sender.'),
        ),
    ]
