# Generated by Django 5.2.14 on 2026-09-29 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
        ('subscribers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
            ],
            options={
                'verbose_name': 'Subscriber',
                'verbose_name_plural': 'Subscribers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('subscribers.subscriber',),
        ),
    ]
