# Generated by Django 5.2.15 on 2026-06-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='sponsors/')),
                ('website', models.URLField(blank=True)),
                ('tagline', models.CharField(blank=True, max_length=300)),
                ('tier', models.CharField(choices=[('platinum', 'Platinum'), ('gold', 'Gold'), ('silver', 'Silver'), ('community', 'Community')], default='community', max_length=20)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['tier', 'name'],
            },
        ),
    ]
