# Generated by Django 5.2.14 on 2026-06-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sponsor',
            options={'ordering': ['tier', 'name']},
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='description',
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='event',
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='sponsor',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='tagline',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='tier',
            field=models.CharField(choices=[('platinum', 'Platinum'), ('gold', 'Gold'), ('silver', 'Silver'), ('community', 'Community')], default='community', max_length=20),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
