# Generated by Django 5.2.15 on 2026-08-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='category',
            field=models.CharField(choices=[('global', 'Global Partner'), ('event', 'Event Partner'), ('community_supporter', 'Community Supporter')], default='community_supporter', help_text='Used to group this partner on the Our Partners page.', max_length=30),
        ),
    ]
