# Generated by Django 5.2.14 on 2026-10-07 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0002_sponsor_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The admin/organizer who added this sponsor.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsors', to=settings.AUTH_USER_MODEL),
        ),
    ]
