# Generated by Django 5.2.15 on 2026-06-22 12:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(unique=True)),
                ('excerpt', models.TextField(blank=True)),
                ('content', models.TextField(blank=True, help_text="Legacy plain-text field — leave blank if you're using the Sections below. If filled, it renders above any sections.")),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('author', models.CharField(blank=True, max_length=200)),
                ('published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(unique=True)),
                ('excerpt', models.TextField(blank=True)),
                ('content', models.TextField(blank=True, help_text="Legacy plain-text field — leave blank if you're using the Sections below. If filled, it renders above any sections.")),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('estimated_minutes', models.PositiveSmallIntegerField(blank=True, help_text='Estimated read/build time in minutes, shown on the card and detail page.', null=True)),
                ('cover_image', models.ImageField(blank=True, help_text='Optional banner shown at the top of the tutorial detail page.', null=True, upload_to='tutorials/')),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Sections are displayed lowest → highest. 0 = first.')),
                ('heading', models.CharField(blank=True, help_text='Optional section heading (renders as <h2>).', max_length=300)),
                ('body', models.TextField(blank=True, help_text='Prose for this section. Leave a blank line between paragraphs — they will each render as separate <p> tags.')),
                ('code_block', models.TextField(blank=True, help_text='Paste your code here exactly as you want it to appear. Indentation and line breaks are preserved.')),
                ('language', models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('html', 'HTML'), ('css', 'CSS'), ('bash', 'Bash / Shell'), ('json', 'JSON'), ('sql', 'SQL'), ('plaintext', 'Plain text')], default='python', help_text='Syntax-highlighting language for the code block above.', max_length=20)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='content.blogpost')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TutorialSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Sections are displayed lowest → highest. 0 = first.')),
                ('heading', models.CharField(blank=True, help_text='Optional section heading (renders as <h2> on the page).', max_length=300)),
                ('body', models.TextField(blank=True, help_text='Prose for this section. Leave a blank line between paragraphs — they will each render as separate <p> tags.')),
                ('code_block', models.TextField(blank=True, help_text='Paste your code here exactly as you want it to appear. Indentation and line breaks are preserved. Leave blank if no code for this section.')),
                ('language', models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('html', 'HTML'), ('css', 'CSS'), ('bash', 'Bash / Shell'), ('json', 'JSON'), ('sql', 'SQL'), ('plaintext', 'Plain text')], default='python', help_text='Syntax-highlighting language for the code block above.', max_length=20)),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='content.tutorial')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
