# Generated by Django 5.2.14 on 2026-08-01 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(unique=True)),
                ('tagline', models.CharField(blank=True, help_text="Short headline in the hero, e.g. 'Build your first app this weekend!'", max_length=300)),
                ('image', models.ImageField(blank=True, help_text='Banner image shown on the event card and detail page hero', null=True, upload_to='events/')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=300)),
                ('venue_name', models.CharField(blank=True, help_text='e.g. Code Campus Nigeria, Floor 3', max_length=300)),
                ('city', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True, help_text='General description shown above the schedule')),
                ('day1_title', models.CharField(blank=True, help_text='e.g. Installation Party & Setup', max_length=200)),
                ('day1_schedule', models.TextField(blank=True, help_text='One item per line...')),
                ('day2_title', models.CharField(blank=True, help_text='e.g. Python & Django Workshop', max_length=200)),
                ('day2_schedule', models.TextField(blank=True, help_text='One item per line')),
                ('day3_title', models.CharField(blank=True, help_text='e.g. Project Showcase...', max_length=200)),
                ('day3_schedule', models.TextField(blank=True, help_text='One item per line...')),
                ('what_you_learn', models.TextField(blank=True)),
                ('who_should_apply', models.TextField(blank=True)),
                ('faq', models.TextField(blank=True)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('application_open', models.BooleanField(default=True)),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, help_text='The approved event organizer responsible for this specific execution.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
    ]
