# Generated by Django 5.2.15 on 2026-08-06 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='custom_css',
            field=models.TextField(blank=True, help_text='Custom CSS to include on the event page'),
        ),
        migrations.AddField(
            model_name='event',
            name='custom_html',
            field=models.TextField(blank=True, help_text='Custom HTML to include on the event page'),
        ),
        migrations.AddField(
            model_name='event',
            name='schedule_title',
            field=models.CharField(blank=True, default='', help_text="Override the 'Schedule' section title", max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='sponsors_title',
            field=models.CharField(blank=True, default='', help_text="Override the 'Sponsors' section title", max_length=255),
        ),
    ]
