# Generated by Django 5.2.15 on 2026-08-09 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0002_alter_coach_options'),
        ('content', '0003_event_custom_css_event_custom_html_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(blank=True, help_text="e.g. 'Workshop Participant, Abuja 2025' or 'Mentor'", max_length=200)),
                ('intro', models.TextField(help_text="Short introduction to the person's journey and work (2-3 sentences).")),
                ('photo', models.ImageField(blank=True, null=True, upload_to='stories/')),
                ('link', models.URLField(blank=True, help_text='URL to the full story — a blog post or external article.')),
                ('published', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Lower = shown first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Stories',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='attendees_count',
            field=models.PositiveIntegerField(default=0, help_text='Verified number of people who attended this event. Update after the event.'),
        ),
        migrations.AddField(
            model_name='event',
            name='country',
            field=models.CharField(blank=True, help_text='Country where the event is held (used for map and footer counters).', max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='GPS latitude — used on the event map page.', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='GPS longitude — used on the event map page.', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='resource_type',
            field=models.CharField(choices=[('workshop_tutorial', 'Python & AI Tutorial'), ('organisers_manual', "Organiser's Manual"), ('mentoring_guide', 'Mentoring Guide'), ('extension', 'Tutorial Extension')], default='workshop_tutorial', help_text='Classifies this tutorial on the Resources page.', max_length=30),
        ),
        migrations.CreateModel(
            name='EventOrganiser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(blank=True, help_text='e.g. Lead Organiser, Logistics', max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='organisers/')),
                ('profile_url', models.URLField(blank=True, help_text='LinkedIn, Twitter or personal site.')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organisers', to='content.event')),
            ],
            options={
                'verbose_name': 'Event Organiser',
                'verbose_name_plural': 'Event Organisers',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='EventPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='event_partners/')),
                ('website', models.URLField(blank=True)),
                ('description', models.TextField(blank=True, help_text="Accurate description of this partner's contribution to this event.")),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_partners', to='content.event')),
            ],
            options={
                'verbose_name': 'Event Partner',
                'verbose_name_plural': 'Event Partners',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='EventMentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_assignments', to='coach.coach')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_mentors', to='content.event')),
            ],
            options={
                'verbose_name': 'Event Mentor',
                'verbose_name_plural': 'Event Mentors',
                'ordering': ['order'],
                'unique_together': {('event', 'coach')},
            },
        ),
    ]
