# Generated by Django 5.2.14 on 2026-06-09 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_event_options_remove_event_date_event_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='application_deadline',
            field=models.DateField(blank=True, help_text='Date applications close', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='application_open',
            field=models.BooleanField(default=True, help_text='Show the Register Interest button on the event page'),
        ),
        migrations.AddField(
            model_name='event',
            name='city',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='day1_schedule',
            field=models.TextField(blank=True, help_text='One item per line, e.g.\n09:00 — Registration\n10:00 — Welcome Session'),
        ),
        migrations.AddField(
            model_name='event',
            name='day1_title',
            field=models.CharField(blank=True, help_text='e.g. Installation Party & Setup', max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='day2_schedule',
            field=models.TextField(blank=True, help_text='One item per line'),
        ),
        migrations.AddField(
            model_name='event',
            name='day2_title',
            field=models.CharField(blank=True, help_text='e.g. Python & Django Workshop', max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='day3_schedule',
            field=models.TextField(blank=True, help_text='One item per line — leave blank if no Day 3'),
        ),
        migrations.AddField(
            model_name='event',
            name='day3_title',
            field=models.CharField(blank=True, help_text='e.g. Project Showcase — leave blank if no Day 3', max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='faq',
            field=models.TextField(blank=True, help_text='Q&A pairs separated by a blank line. Format:\nQ: Do I need experience?\nA: No, beginners are welcome!\n\nQ: Should I bring a laptop?\nA: Yes please.'),
        ),
        migrations.AddField(
            model_name='event',
            name='tagline',
            field=models.CharField(blank=True, help_text="Short headline in the hero, e.g. 'Build your first app this weekend!'", max_length=300),
        ),
        migrations.AddField(
            model_name='event',
            name='venue_name',
            field=models.CharField(blank=True, help_text='e.g. Tech Hub Lagos, Floor 3', max_length=300),
        ),
        migrations.AddField(
            model_name='event',
            name='what_you_learn',
            field=models.TextField(blank=True, help_text='One bullet per line, e.g.\nPython fundamentals\nDjango models and views'),
        ),
        migrations.AddField(
            model_name='event',
            name='who_should_apply',
            field=models.TextField(blank=True, help_text='One bullet per line, e.g.\nComplete beginners\nPeople switching careers'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, help_text='General description shown above the schedule'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, help_text='Banner image shown on the event card and detail page hero', null=True, upload_to='events/'),
        ),
    ]
