# Generated by Django 5.2.14 on 2026-06-11 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_event_application_deadline_event_application_open_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Optional banner shown at the top of the tutorial detail page.', null=True, upload_to='tutorials/'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='estimated_minutes',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Estimated read/build time in minutes, shown on the card and detail page.', null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(blank=True, help_text="Legacy plain-text field — leave blank if you're using the Sections below. If filled, it renders above any sections."),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='content',
            field=models.TextField(blank=True, help_text="Legacy plain-text field — leave blank if you're using the Sections below. If filled, it renders above any sections."),
        ),
        migrations.CreateModel(
            name='BlogSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Sections are displayed lowest → highest. 0 = first.')),
                ('heading', models.CharField(blank=True, help_text='Optional section heading (renders as <h2>).', max_length=300)),
                ('body', models.TextField(blank=True, help_text='Prose for this section. Leave a blank line between paragraphs — they will each render as separate <p> tags.')),
                ('code_block', models.TextField(blank=True, help_text='Paste your code here exactly as you want it to appear. Indentation and line breaks are preserved.')),
                ('language', models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('html', 'HTML'), ('css', 'CSS'), ('bash', 'Bash / Shell'), ('json', 'JSON'), ('sql', 'SQL'), ('plaintext', 'Plain text')], default='python', help_text='Syntax-highlighting language for the code block above.', max_length=20)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='content.blogpost')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TutorialSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Sections are displayed lowest → highest. 0 = first.')),
                ('heading', models.CharField(blank=True, help_text='Optional section heading (renders as <h2> on the page).', max_length=300)),
                ('body', models.TextField(blank=True, help_text='Prose for this section. Leave a blank line between paragraphs — they will each render as separate <p> tags.')),
                ('code_block', models.TextField(blank=True, help_text='Paste your code here exactly as you want it to appear. Indentation and line breaks are preserved. Leave blank if no code for this section.')),
                ('language', models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('html', 'HTML'), ('css', 'CSS'), ('bash', 'Bash / Shell'), ('json', 'JSON'), ('sql', 'SQL'), ('plaintext', 'Plain text')], default='python', help_text='Syntax-highlighting language for the code block above.', max_length=20)),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='content.tutorial')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
