# Generated by Django 5.2.5 on 2026-08-11 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_story_event_attendees_count_event_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('location_identifier', models.CharField(help_text="e.g. 'home_about_section', 'footer_text'", max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Website Content',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteMenus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(help_text='Can be a named URL pattern or absolute URL', max_length=255)),
                ('position', models.CharField(choices=[('header', 'Header'), ('footer', 'Footer'), ('sidebar', 'Sidebar')], default='header', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Website Menus',
                'ordering': ['position', 'order'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='eventmentor',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='eventmentor',
            name='coach',
        ),
        migrations.RemoveField(
            model_name='eventmentor',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventorganiser',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventpartner',
            name='event',
        ),
        migrations.DeleteModel(
            name='Story',
        ),
        migrations.DeleteModel(
            name='EventMentor',
        ),
        migrations.DeleteModel(
            name='EventOrganiser',
        ),
        migrations.DeleteModel(
            name='EventPartner',
        ),
    ]
