# Generated by Django 5.2.14 on 2026-06-17 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_tutorial_cover_image_tutorial_estimated_minutes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='venue_name',
            field=models.CharField(blank=True, help_text='e.g. Code Campus Nigeria, Floor 3', max_length=300),
        ),
    ]
