# Generated by Django 5.2.5 on 2026-08-11 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_websitecontent_websitemenus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorialsection',
            name='tutorial',
        ),
        migrations.DeleteModel(
            name='Tutorial',
        ),
        migrations.DeleteModel(
            name='TutorialSection',
        ),
    ]
