# Generated by Django 5.2.15 on 2026-09-02 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0002_alter_coach_options'),
        ('content', '0006_remove_tutorialsection_tutorial_delete_tutorial_and_more'),
        ('sponsors', '0002_sponsor_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCoach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, help_text="Override the coach's default role for this event, e.g. 'Lead Mentor'.", max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Lower numbers appear first in the coach list.')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_assignments', to='coach.coach')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_coaches', to='content.event')),
            ],
            options={
                'verbose_name': 'Event Coach',
                'verbose_name_plural': 'Event Coaches',
                'ordering': ['order'],
                'unique_together': {('event', 'coach')},
            },
        ),
        migrations.AddField(
            model_name='event',
            name='coaches',
            field=models.ManyToManyField(blank=True, related_name='events', through='content.EventCoach', to='coach.coach'),
        ),
        migrations.CreateModel(
            name='EventSponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, help_text="Short blurb about this sponsor's contribution to this specific event.", max_length=300)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Lower numbers appear first in the sponsor list.')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_sponsors', to='content.event')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_appearances', to='sponsors.sponsor')),
            ],
            options={
                'verbose_name': 'Event Sponsor',
                'verbose_name_plural': 'Event Sponsors',
                'ordering': ['order'],
                'unique_together': {('event', 'sponsor')},
            },
        ),
        migrations.AddField(
            model_name='event',
            name='sponsors',
            field=models.ManyToManyField(blank=True, related_name='events', through='content.EventSponsor', to='sponsors.sponsor'),
        ),
    ]
