# Generated by Django 5.2.14 on 2026-06-18 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_alter_event_venue_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='The approved event organizer responsible for this specific execution.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='application_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='application_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='day1_schedule',
            field=models.TextField(blank=True, help_text='One item per line...'),
        ),
        migrations.AlterField(
            model_name='event',
            name='day3_schedule',
            field=models.TextField(blank=True, help_text='One item per line...'),
        ),
        migrations.AlterField(
            model_name='event',
            name='day3_title',
            field=models.CharField(blank=True, help_text='e.g. Project Showcase...', max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='faq',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='what_you_learn',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='who_should_apply',
            field=models.TextField(blank=True),
        ),
    ]
