# Generated by Django 5.2.5 on 2026-09-03 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_event_coach_sponsor'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.CharField(default='Start with Python. Build with AI.', help_text='Short tagline shown under the Python Weekend logo in the footer.', max_length=255)),
                ('copyright_text', models.CharField(default='© {year} Python Weekend · An initiative of Code Campus International.', help_text='Copyright line at the bottom of every page. Use {year} as a placeholder and it will be replaced with the current year.', max_length=500)),
                ('facebook_url', models.URLField(blank=True, default='https://facebook.com', help_text='Facebook page URL.')),
                ('instagram_url', models.URLField(blank=True, default='https://instagram.com', help_text='Instagram profile URL.')),
                ('twitter_url', models.URLField(blank=True, default='https://x.com', help_text='X / Twitter profile URL.')),
                ('linkedin_url', models.URLField(blank=True, default='https://linkedin.com', help_text='LinkedIn page URL.')),
            ],
            options={
                'verbose_name': 'Footer Configuration',
                'verbose_name_plural': 'Footer Configuration',
            },
        ),
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Home'), ('about', 'About'), ('contact', 'Contact'), ('support', 'Support Us'), ('partners', 'Partners'), ('organise', 'Organise'), ('contribute', 'Contribute'), ('resources', 'Resources'), ('newsletter', 'Newsletter'), ('faq', 'FAQ'), ('coc', 'Code of Conduct'), ('jobs', 'Jobs'), ('global', 'Global (all pages)')], db_index=True, default='home', help_text='Which page this content block belongs to.', max_length=50)),
                ('key', models.CharField(help_text="Unique machine identifier used in templates, e.g. 'home_hero_headline'. Do not change this after creation.", max_length=100, unique=True)),
                ('label', models.CharField(help_text="Human-readable name shown as the field label in the admin list, e.g. 'Hero — Main Headline'.", max_length=255)),
                ('admin_help_text', models.CharField(blank=True, help_text="Hint shown to the admin when editing this field, e.g. 'The big bold headline over the hero image. Keep it inspiring, under 12 words.'", max_length=500)),
                ('value', models.TextField(blank=True, help_text='The content that will appear on the page. Leave blank to use the template default.')),
                ('content_type', models.CharField(choices=[('text', 'Plain text (single line)'), ('richtext', 'Rich text (multi-paragraph)')], default='text', help_text="'Plain text' for short labels/headings; 'Rich text' for paragraphs.", max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page Content',
                'verbose_name_plural': 'Page Content',
                'ordering': ['page', 'key'],
            },
        ),
        migrations.AlterModelOptions(
            name='websitecontent',
            options={'managed': True, 'verbose_name': 'Website Content (Legacy)', 'verbose_name_plural': 'Website Content (Legacy)'},
        ),
        migrations.AlterModelOptions(
            name='websitemenus',
            options={'managed': True, 'verbose_name': 'Website Menu (Legacy)', 'verbose_name_plural': 'Website Menus (Legacy)'},
        ),
        migrations.AlterField(
            model_name='websitecontent',
            name='location_identifier',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='websitemenus',
            name='url',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='WebsiteMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="Display text shown in the navigation, e.g. 'Support Us'.", max_length=100)),
                ('url', models.CharField(help_text='Absolute path, e.g. /about/ or /events/. Use / for homepage.', max_length=255)),
                ('position', models.CharField(choices=[('header', 'Header'), ('footer', 'Footer')], db_index=True, default='header', help_text='Where this item appears.', max_length=20)),
                ('footer_column', models.CharField(blank=True, help_text="Footer only — the column heading this link belongs to, e.g. 'Python Weekend' or 'Support Us'. Leave blank for header items.", max_length=100)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Lower numbers appear first. Items with the same order are sorted alphabetically.')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this item without deleting it.')),
                ('open_in_new_tab', models.BooleanField(default=False, help_text='Check to open this link in a new browser tab (e.g. for external links).')),
                ('parent', models.ForeignKey(blank=True, help_text='Leave blank for top-level items. Set to a top-level header item to make this a dropdown child.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='content.websitemenuitem')),
            ],
            options={
                'verbose_name': 'Website Menu Item',
                'verbose_name_plural': 'Website Menu Items',
                'ordering': ['position', 'order', 'label'],
            },
        ),
    ]
