# Generated by Django 5.2.5 on 2026-09-03 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_seed_content_and_menus'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutContent',
            fields=[
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'About — Website Content',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.pagecontent',),
        ),
        migrations.CreateModel(
            name='CoCContent',
            fields=[
            ],
            options={
                'verbose_name': 'Code of Conduct',
                'verbose_name_plural': 'Code of Conduct — Website Content',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.pagecontent',),
        ),
        migrations.CreateModel(
            name='ContributeContent',
            fields=[
            ],
            options={
                'verbose_name': 'Contribute',
                'verbose_name_plural': 'Contribute — Website Content',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.pagecontent',),
        ),
        migrations.CreateModel(
            name='FAQContent',
            fields=[
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ — Website Content',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.pagecontent',),
        ),
        migrations.CreateModel(
            name='GlobalContent',
            fields=[
            ],
            options={
                'verbose_name': 'Global / Footer Text',
                'verbose_name_plural': 'Global / Footer Text — Website Content',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.pagecontent',),
        ),
        migrations.CreateModel(
            name='HomeContent',
            fields=[
            ],
            options={
                'verbose_name': 'Home',
                'verbose_name_plural': 'Home — Website Content',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.pagecontent',),
        ),
        migrations.CreateModel(
            name='NewsletterContent',
            fields=[
            ],
            options={
                'verbose_name': 'Newsletter',
                'verbose_name_plural': 'Newsletter — Website Content',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.pagecontent',),
        ),
        migrations.CreateModel(
            name='OrganiseContent',
            fields=[
            ],
            options={
                'verbose_name': 'Organise',
                'verbose_name_plural': 'Organise — Website Content',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.pagecontent',),
        ),
        migrations.CreateModel(
            name='PartnersContent',
            fields=[
            ],
            options={
                'verbose_name': 'Partners',
                'verbose_name_plural': 'Partners — Website Content',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.pagecontent',),
        ),
        migrations.CreateModel(
            name='ResourcesContent',
            fields=[
            ],
            options={
                'verbose_name': 'Resources',
                'verbose_name_plural': 'Resources — Website Content',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.pagecontent',),
        ),
        migrations.CreateModel(
            name='SupportContent',
            fields=[
            ],
            options={
                'verbose_name': 'Support Us',
                'verbose_name_plural': 'Support Us — Website Content',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.pagecontent',),
        ),
        migrations.RemoveField(
            model_name='event',
            name='custom_css',
        ),
        migrations.AlterField(
            model_name='event',
            name='application_deadline',
            field=models.DateField(blank=True, help_text='The date when applications will close.', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='application_open',
            field=models.BooleanField(default=True, help_text="If checked, the 'Register Interest' button will be visible on the event page."),
        ),
        migrations.AlterField(
            model_name='event',
            name='custom_html',
            field=models.TextField(blank=True, help_text='Custom HTML block (Tailwind CSS classes supported) to include on the event page. You do not need a separate CSS field.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='faq',
            field=models.TextField(blank=True, help_text='Q&A pairs separated by a blank line. Format:\nQ: Do I need experience?\nA: No, beginners are welcome!'),
        ),
        migrations.AlterField(
            model_name='event',
            name='what_you_learn',
            field=models.TextField(blank=True, help_text='List the skills participants will gain. Enter one item per line.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='who_should_apply',
            field=models.TextField(blank=True, help_text='Describe the ideal candidate. Enter one item per line.'),
        ),
    ]
