# Generated by Django 5.2.5 on 2026-09-03 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_remove_custom_css_add_help_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutContent',
        ),
        migrations.DeleteModel(
            name='CoCContent',
        ),
        migrations.DeleteModel(
            name='ContributeContent',
        ),
        migrations.DeleteModel(
            name='FAQContent',
        ),
        migrations.DeleteModel(
            name='GlobalContent',
        ),
        migrations.DeleteModel(
            name='HomeContent',
        ),
        migrations.DeleteModel(
            name='NewsletterContent',
        ),
        migrations.DeleteModel(
            name='OrganiseContent',
        ),
        migrations.DeleteModel(
            name='PartnersContent',
        ),
        migrations.DeleteModel(
            name='ResourcesContent',
        ),
        migrations.DeleteModel(
            name='SupportContent',
        ),
        migrations.AlterModelOptions(
            name='pagecontent',
            options={'ordering': ['page', 'key'], 'verbose_name': 'Website Content', 'verbose_name_plural': 'Website Content'},
        ),
        migrations.AlterModelOptions(
            name='websitemenuitem',
            options={'ordering': ['position', 'order', 'label'], 'verbose_name': 'Website Menu', 'verbose_name_plural': 'Website Menus'},
        ),
    ]
