# Generated by Django 5.2.14 on 2026-09-25 12:47

from django.db import migrations


def create_page_content(apps, schema_editor):
    PageContent = apps.get_model('content', 'PageContent')
    PageContent.objects.get_or_create(
        identifier='code_campus_url',
        defaults={
            'label': 'Footer — Code Campus URL',
            'value': 'https://codecampus.com.ng/',
            'admin_help_text': 'The URL for the official Code Campus link in the footer.',
            'content_type': 'text',
        }
    )

class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_revert_proxy_models'),
    ]

    operations = [
        migrations.RunPython(create_page_content, reverse_code=migrations.RunPython.noop),
    ]
