# Generated by Django 5.2.14 on 2026-09-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_sync_flatpages_content_and_cleanup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='custom_html',
            field=models.TextField(blank=True, help_text='Custom HTML block to include on the event page (supports inline CSS & Tailwind classes). Renders alongside normal event description without overriding it.'),
        ),
        migrations.AlterField(
            model_name='footerconfig',
            name='copyright_text',
            field=models.CharField(default='© {year} Python Weekend · An initiative of Code Campus International.', help_text='Copyright line shown at the bottom of every page. Use {year} as a placeholder and it will be replaced with the current year. The static fallback in the template renders "Code Campus International" as a clickable link automatically.', max_length=500),
        ),
    ]
