# Generated by Django 5.2.14 on 2026-10-05 08:43

from django.db import migrations


def seed_missing_content(apps, schema_editor):
    PageContent = apps.get_model('content', 'PageContent')
    missing_items = [
        # Resources
        ("resources", "resources_hero_heading", "text", "Hero Heading (Resources)", "Resources"),
        ("resources", "resources_hero_intro", "text", "Hero Intro (Resources)", "Python Weekend resources are designed to help complete beginners learn during a workshop and continue practising afterwards."),
        
        # Jobs
        ("jobs", "jobs_hero_heading", "text", "Hero Heading (Jobs)", "Job Board"),
        ("jobs", "jobs_hero_intro", "text", "Hero Intro (Jobs)", "Opportunities for Python, AI, and entry-level technology roles."),
        
        # Partners
        ("partners", "partners_hero_heading", "text", "Hero Heading (Partners)", "Our Partners"),
        ("partners", "partners_hero_intro", "text", "Hero Intro (Partners)", "Our partners are organisations that support Python Weekend through programme sponsorship, local event sponsorship, or approved in-kind contributions."),
    ]
    for page, key, ctype, label, val in missing_items:
        PageContent.objects.get_or_create(
            key=key,
            defaults={
                "page": page,
                "content_type": ctype,
                "label": label,
                "value": val,
                "admin_help_text": f"Edit {label}",
            }
        )

def reverse_seed(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_alter_event_custom_html_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_missing_content, reverse_code=reverse_seed),
    ]
