# Generated by Antigravity manually
import re
from django.db import migrations
from django.utils.html import strip_tags

def clean_flatpage_content(apps, schema_editor):
    FlatPage = apps.get_model('flatpages', 'FlatPage')
    for fp in FlatPage.objects.all():
        if fp.content:
            # Strip HTML tags but preserve some spacing
            text = fp.content.replace('</p>', '\n\n').replace('<br>', '\n').replace('</div>', '\n\n')
            text = strip_tags(text)
            # Clean up excessive newlines
            text = re.sub(r'\n{3,}', '\n\n', text).strip()
            
            # Special case for FAQ: format correctly if it looks like the old FAQ content
            if fp.url == '/faq/' and 'Python Weekend workshops are organised' in text:
                text = """Q: How can I register?
A: Find the workshop happening in your city and open its event page. If applications are open, you will see an application link. If no application link is displayed, registration has not opened or has already closed.

Q: I missed the deadline. Can I still apply?
A: Usually not. Local teams need time to review applications, confirm participants and prepare the workshop. You can subscribe to the newsletter to hear about future events.

Q: I want to mentor or sponsor an event. What should I do?
A: Contact the local organising team through the event page. They will tell you what support is needed.

Q: I am following the tutorial and my code is not working. Can the central team debug it?
A: The central team primarily supports local organisers and maintains programme resources. Use the official community support channel when available, or ask for help through the relevant workshop community.

Q: Who is Python Weekend for?
A: Python Weekend is for complete beginners who want to learn Python and understand how it can be used in artificial intelligence. Students, professionals, founders, creatives, job seekers and people changing careers are welcome to apply.

Q: Is Python Weekend only for women?
A: No. Python Weekend welcomes people of all genders. We intentionally encourage women and people from communities with limited access to technology education because a more inclusive learning environment strengthens the technology community.

Q: Is Python Weekend inclusive of transgender and nonbinary people?
A: Yes. Python Weekend welcomes people of every gender identity. All participants, mentors, organisers and partners must follow the Code of Conduct.

Q: Is there an age limit?
A: Eligibility may vary by local event. Check the relevant event page before applying. Where minors are accepted, the local team must state any consent or safeguarding requirements.

Q: Is Python Weekend free?
A: Official Python Weekend workshops are free to selected participants. Local teams may secure sponsors and partners to cover the cost of delivering the event.

Q: Do I need previous programming experience?
A: No. The workshop is designed for people who are learning to program for the first time.

Q: Will I become a Python or AI expert in one weekend?
A: No. Python Weekend provides a practical beginning. You will learn essential concepts, complete a guided project and leave with a clearer path for continued learning.

Q: Can I organise Python Weekend in my city?
A: Yes. Read the Organiser's Manual and submit an application to organise a workshop. Approval is required before using the Python Weekend name and brand for an event."""
            fp.content = text
            fp.save()

def reverse_func(apps, schema_editor):
    pass

class Migration(migrations.Migration):
    dependencies = [
        ('content', '0016_add_missing_page_content'),
        ('flatpages', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(clean_flatpage_content, reverse_func),
    ]
