# Generated by Antigravity manually
import re
from django.db import migrations

def clean_flatpage_newlines(apps, schema_editor):
    FlatPage = apps.get_model('flatpages', 'FlatPage')
    for fp in FlatPage.objects.all():
        if fp.content:
            # Normalize Windows newlines
            text = fp.content.replace('\r\n', '\n')
            
            # Squeeze multiple newlines (3 or more) down to 2
            text = re.sub(r'\n{3,}', '\n\n', text).strip()
            
            # For the About page, let's also remove extra spaces at the beginning of lines
            text = '\n'.join(line.strip() for line in text.split('\n'))
            
            fp.content = text
            fp.save()

def reverse_func(apps, schema_editor):
    pass

class Migration(migrations.Migration):
    dependencies = [
        ('content', '0017_clean_flatpage_html'),
        ('flatpages', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(clean_flatpage_newlines, reverse_func),
    ]
