# Generated by Django 5.2.14 on 2026-10-05 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_clean_flatpage_newlines'),
    ]

    operations = [
    ]
