# Generated by Django 5.2.14 on 2026-10-05 11:10

import re
from django.db import migrations


def strip_html_from_flatpages(apps, schema_editor):
    FlatPage = apps.get_model("flatpages", "FlatPage")
    for fp in FlatPage.objects.all():
        if fp.url not in ["/support/", "/support-us/", "/partners/"]:
            text = re.sub(r'<[^>]+>', ' ', fp.content)
            lines = [line.strip() for line in text.splitlines()]
            text = '\n\n'.join([line for line in lines if line])
            fp.content = text
            fp.save()

class Migration(migrations.Migration):

    dependencies = [
        ('content', '0019_empty_flatpages_html'),
        ('flatpages', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(strip_html_from_flatpages, reverse_code=migrations.RunPython.noop),
    ]
