# Generated by Django 5.2.14 on 2026-10-05 11:20

import re
from django.db import migrations


def strip_html_from_partners(apps, schema_editor):
    FlatPage = apps.get_model("flatpages", "FlatPage")
    for fp in FlatPage.objects.filter(url__in=["/support/", "/support-us/", "/partners/"]):
        text = re.sub(r'<[^>]+>', ' ', fp.content)
        lines = [line.strip() for line in text.splitlines()]
        text = '\n\n'.join([line for line in lines if line])
        fp.content = text
        fp.save()

class Migration(migrations.Migration):

    dependencies = [
        ('content', '0020_remove_flatpage_html'),
        ('flatpages', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(strip_html_from_partners, reverse_code=migrations.RunPython.noop),
    ]
