# Generated by Django 5.2.17 on 2026-10-07 09:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0021_remove_all_flatpage_html'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='co_organizers',
            field=models.ManyToManyField(blank=True, help_text='Co-organizers assigned to help manage this event.', related_name='co_organized_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='page',
            field=models.CharField(choices=[('home', 'Home'), ('about', 'About'), ('support', 'Support Us'), ('partners', 'Partners'), ('contribute', 'Contribute'), ('resources', 'Resources'), ('newsletter', 'Newsletter'), ('faq', 'FAQ'), ('coc', 'Code of Conduct'), ('jobs', 'Jobs'), ('global', 'Global (all pages)')], db_index=True, default='home', help_text='Which page this content block belongs to.', max_length=50),
        ),
    ]
