# Generated by Django 5.2.17 on 2026-10-08 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0023_blogpost_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='attendees_count',
        ),
        migrations.AddField(
            model_name='event',
            name='expected_attendees',
            field=models.PositiveIntegerField(default=50, help_text='Target number of expected attendees planned for this event.'),
        ),
    ]
